environment:
  name: prod
  project: cdf-bootcamp-02-prod
  type: prod
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      CDF_PROJECT: cdf-bootcamp-02-prod
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      CDF_URL: https://westeurope-1.cognitedata.com
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env

      # Groups
      data_developer_source_id: 773a7337-9be6-4338-ac62-b51b0affdbd1
      data_pipeline_oee_source_id: 29936438-051b-4aea-8727-275b9a5b09b8
      readwrite_source_id: 43ecd0eb-65c6-4ff0-aece-a168107fa753
      readonly_source_id: 6da312e0-3695-4642-8626-9ca75c922520
      icapi_extractors_source_id: 834031d6-3536-4828-b77f-b37638ffea6f

      # Client Id's (App registrations or Service Principals)
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env

      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env

      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
